# Dockerfile for Nginx

# Use the official Nginx image as a parent image
FROM nginx:latest

# Copy the custom Nginx configuration file into the container
COPY nginx.conf /etc/nginx/conf.d/default.conf
