version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - djangonetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
      until pg_isready -h db -U myuser; do
        echo Waiting for database;
        sleep 2;
      done;
      python manage.py makemigrations home articles &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput --clear &&
      gunicorn --bind 0.0.0.0:8000 cms.wsgi:application
      "
    volumes:
      - ./djangocms:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - djangonetwork
    environment:
      DATABASE_NAME: mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_HOST: db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - djangonetwork

networks:
  djangonetwork:
    driver: bridge

volumes:
  db_data:
